name: Build slides

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install mdslides
          mkdir -p slides
          mdslides slides.md --ouput_dir ./slides/
      - name: Configure github
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit BUMP Version & Push
        run: |
          git add slides/*
          git commit -m "Deploy slides"
          git push origin gh-pages
